services:
  - type: web
    name: beechler-website
    env: SPA
    buildCommand: npm run build
    staticPublishPath: build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html